### ISSUE TITLE
pylast.WSError: Invalid parameters - Your request is missing a required parameter

### ISSUE THREAD

**Issue by spkane** [ronilaukkarinen/pianobar-osx#1]
I haven't dug into this yet, but after getting all this setup, I am seeing this error after each song starts:

```
|>  Song:Lounge Act Artist:Nirvana Album:Nevermind
Traceback (most recent call last):
  File "/Users/skane/.config/pianobar/events.py", line 72, in <module>
    main()
  File "/Users/skane/.config/pianobar/events.py", line 54, in main
    network.update_now_playing(artist = artist, album = album, title = title, duration = song_duration)
  File "/Users/skane/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pylast-2.4.0-py3.6.egg/pylast/__init__.py", line 538, in update_now_playing
  File "/Users/skane/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pylast-2.4.0-py3.6.egg/pylast/__init__.py", line 954, in execute
  File "/Users/skane/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pylast-2.4.0-py3.6.egg/pylast/__init__.py", line 943, in _download_response
  File "/Users/skane/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pylast-2.4.0-py3.6.egg/pylast/__init__.py", line 973, in _check_response_for_errors
pylast.WSError: Invalid parameters - Your request is missing a required parameter
#   -00:20/02:37
```

**Comment by rollecode** [comment]
Haven't encountered that myself before, hard to say what causes it. What you could do is to narrow it down by removing one line that starts with `network.`, then start to play and see where the error stops. Not that experienced in pylast that I could say right away.

**Comment by spkane** [comment]
This is fixed by following the directions, which have been made a bit clearer now. Note that you need to edit the variables at the top of the `events.py` script.

**Comment by rollecode** [comment]
Thanks Sean!
